# Generated by Django 4.2.21 on 2025-05-14 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='social_links',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='social_links',
        ),
    ]
