# Generated by Django 4.2.21 on 2025-05-19 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0003_sitesetting_facebook_url_sitesetting_github_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='contact_attachments/'),
        ),
    ]
