# Generated by Django 4.2.21 on 2025-07-23 08:55

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0004_contactsubmission_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 200], upload_to='services/'),
        ),
    ]
