# Generated by Django 4.2.21 on 2025-07-23 09:18

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0006_moveablelogo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveablelogo',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[200, 200], upload_to='mvicons/'),
        ),
    ]
