# Generated by Django 4.2.21 on 2025-07-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0007_alter_moveablelogo_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='moveablelogo',
            name='color_code',
            field=models.CharField(default=343, max_length=20),
            preserve_default=False,
        ),
    ]
