# Generated by Django 4.2.21 on 2025-07-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0008_moveablelogo_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandingcasestudy',
            name='description',
        ),
        migrations.RemoveField(
            model_name='brandingcasestudy',
            name='logo',
        ),
        migrations.AddField(
            model_name='brandingcasestudy',
            name='image',
            field=models.ImageField(default=21, upload_to='branding_case_studies/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='brandingcasestudy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
