# Generated by Django 4.2.21 on 2025-07-24 08:31

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0009_remove_brandingcasestudy_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandingcasestudy',
            name='image',
        ),
        migrations.RemoveField(
            model_name='brandingcasestudy',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='brandingcasestudy',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='brandingcasestudy',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 200], upload_to='case_studies/'),
        ),
    ]
