# Generated by Django 4.2.21 on 2025-07-24 08:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0010_remove_brandingcasestudy_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='dribble_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Dribble Profile'),
        ),
    ]
