# Generated by Django 4.2.21 on 2025-08-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0011_sitesetting_dribble_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main heading for About section', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subheading', max_length=255, null=True)),
                ('description', models.TextField(help_text='Detailed description about your company or service')),
                ('image', models.ImageField(blank=True, help_text='Upload an image for the About section', null=True, upload_to='about/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
            },
        ),
    ]
