# Generated by Django 4.2.21 on 2025-08-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0012_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(blank=True, help_text='Include country code, e.g. +1 234 567 890', max_length=20, null=True),
        ),
    ]
