# Generated by Django 4.2.21 on 2025-08-04 08:57

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0013_contactsubmission_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='footer_logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 100], upload_to='site/'),
        ),
    ]
