# Generated by Django 4.2.21 on 2025-08-16 06:17

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0014_sitesetting_footer_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandingCaseStudySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[800, 600], upload_to='case_study_sections/')),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='landingpage.brandingcasestudy')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
