# Generated by Django 4.2.21 on 2025-08-17 10:14

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0016_projectsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='hero_image1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1600, 900], upload_to='hero/'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='hero_image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1600, 900], upload_to='hero/'),
        ),
    ]
