# Generated by Django 4.2.21 on 2025-08-17 11:09

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('landingpage', '0017_sitesetting_hero_image1_sitesetting_hero_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingcasestudy',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload an image for the section. Recommended size: 300x200 pixels.', keep_meta=True, null=True, quality=-1, scale=None, size=[300, 200], upload_to='case_studies/'),
        ),
        migrations.AlterField(
            model_name='brandingcasestudysection',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload an image for the section. Recommended size: 800x600 pixels.', keep_meta=True, null=True, quality=-1, scale=None, size=[800, 600], upload_to='case_study_sections/'),
        ),
        migrations.AlterField(
            model_name='moveablelogo',
            name='icon',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload an image for the section. Recommended size: 200x200 pixels.', keep_meta=True, null=True, quality=-1, scale=None, size=[200, 200], upload_to='mvicons/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload an image for the section. Recommended size: 800x600 pixels.', keep_meta=True, null=True, quality=-1, scale=None, size=[800, 600], upload_to='projects/'),
        ),
        migrations.AlterField(
            model_name='projectsection',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload an image for the section. Recommended size: 800x600 pixels.', keep_meta=True, null=True, quality=-1, scale=None, size=[800, 600], upload_to='project_section/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload an image for the section. Recommended size: 300x200 pixels.', keep_meta=True, null=True, quality=-1, scale=None, size=[300, 200], upload_to='services/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload an image for the section. Recommended size: 1600x900 pixels.', keep_meta=True, null=True, quality=-1, scale=None, size=[1600, 900], upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_image1',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload an image for the section. Recommended size: 1600x900 pixels.', keep_meta=True, null=True, quality=-1, scale=None, size=[1600, 900], upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='hero_image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload an image for the section. Recommended size: 1600x900 pixels.', keep_meta=True, null=True, quality=-1, scale=None, size=[1600, 900], upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload an image for the section. Recommended size: 400x400 pixels.', keep_meta=True, null=True, quality=-1, scale=None, size=[400, 400], upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Upload an image for the section. Recommended size: 200x200 pixels.', keep_meta=True, null=True, quality=-1, scale=None, size=[200, 200], upload_to='testimonials/'),
        ),
    ]
